<?php

return [
    'seo' => [
        'title' => 'David — IT Support & Web Developer',
        'description' => 'Portofolio David, IT Support dan Web Developer di Medan yang berfokus pada infrastruktur, server, jaringan, dan aplikasi Laravel.',
        'canonical' => env('APP_URL', 'http://localhost:8000'),
        'share_image' => 'images/fallback/portfolio-share.webp',
    ],

    'profile' => [
        'name' => 'David',
        'full_name' => env('PORTFOLIO_FULL_NAME', 'David'),
        'initials' => 'DV',
        'eyebrow' => 'IT Support · Infrastructure · Laravel',
        'title' => 'IT Support & Web Developer',
        'summary' => 'Saya membantu operasional tetap berjalan melalui dukungan perangkat, jaringan, server, dan aplikasi web yang praktis.',
        'about' => 'Berpengalaman menangani kebutuhan IT operasional seperti troubleshooting hardware dan software, jaringan, CCTV, printer, serta administrasi server. Saya juga membangun aplikasi Laravel untuk menyederhanakan pencatatan, pelaporan, dan proses kerja sehari-hari.',
        'location' => 'Medan, Sumatera Utara, Indonesia',
        'photo' => 'images/profile/david.webp',
        'cv' => 'documents/cv-david.pdf',
        'available' => filter_var(env('PORTFOLIO_AVAILABLE', true), FILTER_VALIDATE_BOOL),
    ],

    'contact' => [
        'enabled' => filter_var(env('PORTFOLIO_CONTACT_ENABLED', false), FILTER_VALIDATE_BOOL),
        'email' => env('PORTFOLIO_EMAIL'),
        'whatsapp' => env('PORTFOLIO_WHATSAPP'),
        'github' => env('PORTFOLIO_GITHUB'),
        'linkedin' => env('PORTFOLIO_LINKEDIN'),
    ],

    'stats' => [
        ['value' => '5+', 'label' => 'Tahun pengalaman IT'],
        ['value' => '4', 'label' => 'Proyek pilihan'],
        ['value' => '2', 'label' => 'Ekosistem: Windows & Linux'],
    ],

    'skill_groups' => [
        [
            'number' => '01',
            'title' => 'IT Support',
            'description' => 'Menjaga perangkat dan pengguna tetap produktif melalui diagnosis serta penyelesaian masalah yang terstruktur.',
            'skills' => ['Hardware', 'Windows', 'Printer', 'Helpdesk', 'Preventive maintenance'],
        ],
        [
            'number' => '02',
            'title' => 'Network & CCTV',
            'description' => 'Menangani konektivitas lokal, perangkat jaringan, pemantauan, dan troubleshooting lapangan.',
            'skills' => ['LAN', 'Mikrotik', 'CCTV', 'TCP/IP', 'Remote support'],
        ],
        [
            'number' => '03',
            'title' => 'Server & Self-hosting',
            'description' => 'Membangun layanan privat yang dapat dipelihara untuk penyimpanan, akses jarak jauh, dan kebutuhan internal.',
            'skills' => ['Ubuntu Server', 'CasaOS', 'Nextcloud', 'Tailscale', 'MariaDB'],
        ],
        [
            'number' => '04',
            'title' => 'Web Development',
            'description' => 'Membuat aplikasi web yang fokus pada alur kerja, pencatatan data, laporan, dan kemudahan penggunaan.',
            'skills' => ['Laravel', 'PHP', 'Blade', 'MySQL', 'Vite'],
        ],
    ],

    'experience' => [
        [
            'role' => 'IT Support',
            'organization' => 'RSU Bunda Thamrin',
            'period' => 'Sekarang',
            'description' => 'Mendukung kebutuhan teknis operasional, perangkat pengguna, jaringan, CCTV, printer, dan troubleshooting harian.',
        ],
    ],

    'education' => [
        'degree' => 'S1 Teknik Informatika',
        'institution' => 'Universitas Putera Batam',
        'period' => '2014 — 2021',
    ],

    'projects' => [
        [
            'slug' => 'david-sales',
            'number' => '01',
            'title' => 'David Sales',
            'category' => 'Sales tracking',
            'summary' => 'Aplikasi pencatatan penjualan yang mengubah transaksi harian menjadi ringkasan omzet dan laporan yang mudah dibaca.',
            'problem' => 'Pencatatan penjualan sederhana sering tersebar dan sulit dirangkum kembali ketika dibutuhkan.',
            'solution' => 'Menyediakan alur input penjualan, perhitungan otomatis, filter, pencarian, dan fondasi ekspor laporan dalam satu aplikasi.',
            'contribution' => 'Merancang struktur data, alur pencatatan, tampilan dashboard, serta pengalaman penggunaan yang tetap sederhana untuk operasional harian.',
            'features' => ['Pencatatan produk terjual', 'Perhitungan omzet otomatis', 'Pencarian dan filter', 'Fondasi ekspor Excel/PDF'],
            'challenge' => 'Menjaga proses input tetap cepat sekaligus memastikan rekap dan perhitungan dapat dipercaya.',
            'impact' => 'Data penjualan lebih konsisten dan rekap harian dapat dilihat tanpa menghitung ulang secara manual.',
            'technologies' => ['Laravel', 'Blade', 'MySQL', 'Vite'],
            'image' => 'images/projects/david-sales.webp',
            'accent' => '#22d3ee',
            'status' => 'Dalam pengembangan',
            'demo_url' => null,
            'source_url' => null,
        ],
        [
            'slug' => 'finance-panel',
            'number' => '02',
            'title' => 'David Finance Panel',
            'category' => 'Expense management',
            'summary' => 'Panel pencatatan pengeluaran dengan dashboard, kategori, laporan, filter tanggal, dan pembatasan akses pengguna.',
            'problem' => 'Riwayat pengeluaran sulit dipantau ketika catatan harian tidak terhubung dengan laporan dan kategori.',
            'solution' => 'Membangun aplikasi Laravel dengan dashboard 30 hari, laporan, pencarian, kategori, dan role admin/user.',
            'contribution' => 'Menyusun kebutuhan, arsitektur akses berbasis peran, dashboard ringkas, laporan, dan deployment sebagai layanan di home server.',
            'features' => ['Dashboard 30 hari', 'Kategori pengeluaran', 'Filter dan pencarian', 'Hak akses admin/user'],
            'challenge' => 'Membuat hak akses tetap mudah dipahami tanpa menambah kerumitan pada alur pencatatan pengguna biasa.',
            'impact' => 'Pengeluaran lebih mudah ditelusuri dan pola biaya dapat dilihat dari satu dashboard.',
            'technologies' => ['Laravel', 'MariaDB', 'Bootstrap', 'Systemd'],
            'image' => 'images/projects/finance-panel.webp',
            'accent' => '#8b5cf6',
            'status' => 'Berjalan di home server',
            'demo_url' => null,
            'source_url' => null,
        ],
        [
            'slug' => 'wedding-invitation',
            'number' => '03',
            'title' => 'Undangan Digital',
            'category' => 'Interactive website',
            'summary' => 'Undangan pernikahan responsif dengan video cover, musik, countdown, galeri, lokasi, RSVP, dan ucapan.',
            'problem' => 'Undangan digital membutuhkan pengalaman personal yang tetap ringan dan mudah digunakan pada ponsel.',
            'solution' => 'Mengembangkan halaman Laravel responsif dengan nama tamu dinamis, media, formulir RSVP, serta pengelolaan ucapan.',
            'contribution' => 'Merancang pengalaman undangan, membangun halaman Laravel, mengelola media, dan mengoptimalkan interaksi utama untuk ponsel.',
            'features' => ['Nama tamu dinamis', 'Video dan musik', 'RSVP serta ucapan', 'Countdown dan lokasi'],
            'challenge' => 'Menjaga video, musik, dan animasi terasa menarik tanpa memperlambat waktu buka pada jaringan seluler.',
            'impact' => 'Informasi acara tersampaikan dalam satu pengalaman digital yang personal dan mudah dibagikan.',
            'technologies' => ['Laravel', 'JavaScript', 'CSS', 'MySQL'],
            'image' => 'images/projects/wedding-invitation.webp',
            'accent' => '#f59e9e',
            'status' => 'Selesai',
            'demo_url' => null,
            'source_url' => null,
        ],
        [
            'slug' => 'home-server',
            'number' => '04',
            'title' => 'Home Server & Private Cloud',
            'category' => 'Infrastructure',
            'summary' => 'Private cloud rumahan untuk penyimpanan, sinkronisasi, dan akses jarak jauh yang aman.',
            'problem' => 'File keluarga membutuhkan penyimpanan terpusat yang tetap dapat diakses dari luar jaringan rumah.',
            'solution' => 'Menyiapkan Ubuntu Server, CasaOS, Nextcloud, MariaDB, storage eksternal, dan koneksi privat melalui Tailscale.',
            'contribution' => 'Menyiapkan sistem operasi, penyimpanan, container aplikasi, basis data, jaringan privat, serta akses lintas perangkat untuk keluarga.',
            'features' => ['Private cloud Nextcloud', 'Storage eksternal', 'Akses privat Tailscale', 'Layanan otomatis saat boot'],
            'challenge' => 'Menyeimbangkan kemudahan akses keluarga, keamanan jaringan, dan keterbatasan perangkat rumahan.',
            'impact' => 'File dapat disimpan dan diakses lintas perangkat dengan kontrol data yang lebih mandiri.',
            'technologies' => ['Ubuntu Server', 'Nextcloud', 'CasaOS', 'Tailscale'],
            'image' => 'images/projects/home-server.webp',
            'accent' => '#34d399',
            'status' => 'Aktif',
            'demo_url' => null,
            'source_url' => null,
        ],
    ],

    'scene' => [
        'enabled' => true,
        'asset_base_path' => '/models/workspace/kenney',
        'custom_model' => 'models/workspace/custom-workspace.glb',
        'asset_source' => 'Kenney Furniture Kit',
        'asset_source_url' => 'https://kenney.nl/assets/furniture-kit',
        'license' => 'CC0 1.0',
    ],
];
